# Generated by Django 4.1.1 on 2022-09-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_of_class', models.CharField(max_length=1, verbose_name='Буква класса')),
                ('number_of_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='Ф.И.О.')),
                ('photo_of_director', models.ImageField(upload_to='directors_avatars')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=127, verbose_name='Название урока')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('grade', models.IntegerField()),
                ('parents_phone', models.CharField(max_length=300, verbose_name='Номер родителей')),
                ('address', models.CharField(max_length=127, verbose_name='Адрекс')),
                ('photo_of_student', models.ImageField(upload_to='students_avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='Ф.И.О.')),
                ('address', models.CharField(max_length=127, verbose_name='Адрекс')),
                ('phone', models.IntegerField()),
                ('photo_of_teacher', models.ImageField(upload_to='teachers_avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Zauch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='Ф.И.О.')),
                ('photo_of_zauch', models.ImageField(upload_to='directors_avatars')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ManyToManyField(to='mainapp.clas', verbose_name='Класс:')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.director', verbose_name='Директор:')),
                ('lesson', models.ManyToManyField(to='mainapp.lesson', verbose_name='Урок:')),
                ('student', models.ManyToManyField(to='mainapp.student', verbose_name='Ученик:')),
                ('teacher', models.ManyToManyField(to='mainapp.teacher', verbose_name='Учитель:')),
                ('zauchi', models.ManyToManyField(to='mainapp.zauch', verbose_name='Заучи:')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='clas',
            name='class_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Классная руководительница'),
        ),
    ]
