# Generated by Django 3.2.7 on 2022-09-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clas')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
                ('clas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clas')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Имя')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
        ),
        migrations.AddField(
            model_name='clas',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher'),
        ),
    ]
