# Generated by Django 3.2.7 on 2022-09-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_director_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clas', to='mainapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='mainapp.school'),
        ),
    ]
