# Generated by Django 3.2.7 on 2022-09-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220921_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mainapp.clas'),
        ),
    ]
